export enum ErrorCategory {
  VALIDATION = "VALIDATION",
  CONFIGURATION = "CONFIGURATION",
  AUTHENTICATION = "AUTHENTICATION",
  AUTHORIZATION = "AUTHORIZATION",
  NETWORK = "NETWORK",
  TIMEOUT = "TIMEOUT",
  CONFLICT = "CONFLICT",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL = "INTERNAL",
  UNKNOWN = "UNKNOWN",
}
