import { replaceRequired } from "../utils.js";

import type { PMIRDocument, PMIRRenderingContext } from "../types.js";

import type { PMIRSectionRenderer } from "./section-renderer.js";

/**
 * Renders the "Enterprise Handoff" section.
 *
 * Ownership:
 * - Current PMIR Version
 * - Completed Milestone
 * - Next Milestone
 * - Current Phase
 *
 * NOTE:
 * Rich handoff generation will be introduced
 * in PMIR Automation v2.
 */
export class HandoffSection implements PMIRSectionRenderer {
  public render(document: PMIRDocument, context: PMIRRenderingContext): string {
    const handoff = `# PEOS Enterprise Handoff

## Repository State

- PMIR Version: ${context.version}
- Latest Completed Milestone: ${context.completedMilestone.id}
- Next Milestone: ${context.nextMilestone?.id ?? "None"}
- Current Phase: ${context.completedMilestone.phase}

This handoff was generated by the PEOS PMIR Automation Engine.`;

    return replaceRequired(
      document.content,
      /# 22\. Enterprise Handoff[\s\S]*$/,
      handoff,
      "Enterprise Handoff",
    );
  }
}
